# src/core/__init__.py
from .config import API_KEY, ENTRY_TYPE, PREFERRED_MODE, LOG_LEVEL
from .constants import (
    # Constants
    BASE_API, JOIN_WS, AGENT_WS, API_VERSION_URL,
    DEFAULT_ENTRY_TYPE, DEFAULT_PREFERRED_MODE, DEFAULT_ACTION_INTERVAL,
    ACTION_INTERVAL_SECONDS,  # <-- TAMBAHKAN INI
    MIN_RETRY_DELAY, MAX_RETRY_DELAY, RETRY_BACKOFF_MULTIPLIER,
    RECONNECT_RESET_THRESHOLD,
    SCORE_HEAL_BASE, SCORE_HEAL_HP_BONUS,
    SCORE_ATTACK_BASE, SCORE_ATTACK_HP_BONUS,
    SCORE_GUARDIAN_PENALTY, SCORE_ATTACK_KILL_BONUS,
    SCORE_SURVIVAL_BONUS,
    SCORE_LOOT_BASE, SCORE_LOOT_BONUS,
    SCORE_INTERACT_BASE, SCORE_EXPLORE_BASE, SCORE_MOVE_BASE,
    SCORE_CAVE_EXIT,
    CACHE_DIR, LOG_DIR, KNOWLEDGE_PATH,
    DOCS_TO_CACHE,
    AI_LEARNING_RATE, AI_CONFIDENCE_THRESHOLD,
    AI_RISK_THRESHOLD, AI_STRATEGY_SWITCH_INTERVAL,
    ensure_directories
)
from .exceptions import *

__all__ = [
    # Config
    "API_KEY", "ENTRY_TYPE", "PREFERRED_MODE", "LOG_LEVEL",
    # Constants
    "BASE_API", "JOIN_WS", "AGENT_WS", "API_VERSION_URL",
    "DEFAULT_ENTRY_TYPE", "DEFAULT_PREFERRED_MODE", "DEFAULT_ACTION_INTERVAL",
    "ACTION_INTERVAL_SECONDS",
    "MIN_RETRY_DELAY", "MAX_RETRY_DELAY", "RETRY_BACKOFF_MULTIPLIER",
    "RECONNECT_RESET_THRESHOLD",
    "SCORE_HEAL_BASE", "SCORE_HEAL_HP_BONUS",
    "SCORE_ATTACK_BASE", "SCORE_ATTACK_HP_BONUS",
    "SCORE_GUARDIAN_PENALTY", "SCORE_ATTACK_KILL_BONUS",
    "SCORE_SURVIVAL_BONUS",
    "SCORE_LOOT_BASE", "SCORE_LOOT_BONUS",
    "SCORE_INTERACT_BASE", "SCORE_EXPLORE_BASE", "SCORE_MOVE_BASE",
    "SCORE_CAVE_EXIT",
    "CACHE_DIR", "LOG_DIR", "KNOWLEDGE_PATH",
    "DOCS_TO_CACHE",
    "AI_LEARNING_RATE", "AI_CONFIDENCE_THRESHOLD",
    "AI_RISK_THRESHOLD", "AI_STRATEGY_SWITCH_INTERVAL",
    "ensure_directories",
    # Exceptions
    "ClawRoyaleError", "ConfigurationError", "VersionMismatchError",
    "AgentDeadError", "TargetDeadError", "ResumeTargetDeadError",
    "AuthenticationError", "RateLimitError", "NotSelectedError", "GameError"
]
